# PostgreSQL. Versions 9.3 and up are supported.
#
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("ARCHIVE_DB_NAME", "archive_development") %>
    username: <%= ENV.fetch("ARCHIVE_DB_USER", "postgres") %>
    password: <%= ENV.fetch("ARCHIVE_DB_PASSWORD", "password") %>
    host: <%= ENV.fetch("ARCHIVE_DB_HOST", "localhost") %>
    port: <%= ENV.fetch("ARCHIVE_DB_PORT", 5432) %>

  # Secondary connection used by Archive* models
  archive:
    <<: *default
    database: <%= ENV.fetch("ARCHIVE_DB_NAME", "archive_development") %>
    username: <%= ENV.fetch("ARCHIVE_DB_USER", "postgres") %>
    password: <%= ENV.fetch("ARCHIVE_DB_PASSWORD", "password") %>
    host: <%= ENV.fetch("ARCHIVE_DB_HOST", "localhost") %>
    port: <%= ENV.fetch("ARCHIVE_DB_PORT", 5432) %>
    replica: true

# Note: top-level 'archive' section removed; use development.archive above

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: jukebox_test
  username: postgres
  password: password
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
