version: '3.9'

services:
  # Redis for background jobs and ActionCable
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL database for Archive
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: archive_production
    volumes:
      - ${POSTGRES_DATA_PATH:-./postgres_data}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Archive Rails application
  archive:
    build:
      context: .
      dockerfile: Dockerfile
    image: archive:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-password}@db:5432/archive_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      # Storage configuration
      STORAGE_ROOT: ${STORAGE_ROOT:-/rails/storage}
      ACTIVE_STORAGE_SERVICE: ${ACTIVE_STORAGE_SERVICE:-local}
    ports:
      - "3000:80"
    volumes:
      - archive_storage:/rails/storage
      - archive_logs:/rails/log
      # Mount host storage directory if specified
      - ${HOST_STORAGE_PATH:-./storage}:/rails/storage:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Sidekiq worker for Archive app
  sidekiq:
    image: archive:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      archive:
        condition: service_started
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-password}@db:5432/archive_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_LOG_TO_STDOUT: true
      STORAGE_ROOT: ${STORAGE_ROOT:-/rails/storage}
      ACTIVE_STORAGE_SERVICE: ${ACTIVE_STORAGE_SERVICE:-local}
    volumes:
      - archive_logs:/rails/log
      - ${HOST_STORAGE_PATH:-./storage}:/rails/storage:ro
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  pgdata:
  archive_storage:
  archive_logs:
  redis_data:
