 

services:
  # Redis for background jobs and ActionCable
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Expose Redis port to host
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL database for Archive
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: archive_production
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Archive Rails application
  archive:
    # All configuration is provided via environment variables (no env files)
    build:
      context: .
      dockerfile: Dockerfile
    image: archive:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/archive_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      # URL/host configuration
      APP_HOST: ${APP_HOST:-${HOSTNAME:-localhost}}
      APP_PROTOCOL: ${APP_PROTOCOL:-http}
      FORCE_SSL: ${FORCE_SSL:-false}
      ASSUME_SSL: ${ASSUME_SSL:-false}
      FORGERY_ORIGIN_CHECK: ${FORGERY_ORIGIN_CHECK:-false}
      ALLOW_ALL_HOSTS: ${ALLOW_ALL_HOSTS:-true}
      INLINE_AUDIO_PROCESSING: ${INLINE_AUDIO_PROCESSING:-true}
      USE_SIDEKIQ: ${USE_SIDEKIQ:-false}
      # Storage configuration
      STORAGE_ROOT: ${STORAGE_ROOT:-/rails/storage}
      ACTIVE_STORAGE_SERVICE: ${ACTIVE_STORAGE_SERVICE:-local}
      # AWS SES SMTP configuration for email delivery
      AWS_SES_SMTP_HOST: ${AWS_SES_SMTP_HOST:-email-smtp.us-east-2.amazonaws.com}
      AWS_SES_SMTP_PORT: ${AWS_SES_SMTP_PORT:-587}
      AWS_SES_SMTP_DOMAIN: ${AWS_SES_SMTP_DOMAIN:-cavaforge.net}
      AWS_SES_SMTP_USERNAME: ${AWS_SES_SMTP_USERNAME:-}
      AWS_SES_SMTP_PASSWORD: ${AWS_SES_SMTP_PASSWORD:-}
      MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL:-noreply@cavaforge.net}
    ports:
      - "${ARCHIVE_PORT:-3000}:3000"
    volumes:
      - archive_logs:/rails/log
      # Mount host storage directory (must be an absolute host path)
      - ${HOST_STORAGE_PATH}:/rails/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Bucardo replication service is defined in docker-compose.replication.yml (used on slave only)

volumes:
  archive_logs:
  redis_data:
