services:
  # Use custom Postgres image with Perl and Bucardo deps on slave
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres

  bucardo:
    build:
      context: .
      dockerfile: Dockerfile.bucardo
    image: bucardo:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ARCHIVE_ROLE: ${ARCHIVE_ROLE}
      BUCARDO_SYNC_DIRECTION: ${BUCARDO_SYNC_DIRECTION}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BUCARDO_LOCAL_DB_HOST: ${BUCARDO_LOCAL_DB_HOST}
      BUCARDO_LOCAL_DB_PORT: ${BUCARDO_LOCAL_DB_PORT}
      BUCARDO_LOCAL_DB_NAME: ${BUCARDO_LOCAL_DB_NAME}
      BUCARDO_LOCAL_DB_USER: ${BUCARDO_LOCAL_DB_USER}
      BUCARDO_LOCAL_DB_PASS: ${BUCARDO_LOCAL_DB_PASS}
      BUCARDO_MASTER_DB_HOST: ${BUCARDO_MASTER_DB_HOST}
      BUCARDO_MASTER_DB_PORT: ${BUCARDO_MASTER_DB_PORT}
      BUCARDO_MASTER_DB_NAME: ${BUCARDO_MASTER_DB_NAME}
      BUCARDO_MASTER_DB_USER: ${BUCARDO_MASTER_DB_USER}
      BUCARDO_MASTER_DB_PASS: ${BUCARDO_MASTER_DB_PASS}
      PGPASSWORD: ${BUCARDO_LOCAL_DB_PASS}
      PGHOST: ${BUCARDO_LOCAL_DB_HOST}
      PGPORT: ${BUCARDO_LOCAL_DB_PORT}
      PGDATABASE: ${BUCARDO_LOCAL_DB_NAME}
      PGUSER: ${BUCARDO_LOCAL_DB_USER}
    volumes:
      - bucardo_data:/var/lib/bucardo
      - bucardo_logs:/var/log/bucardo
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-U", "bucardo", "-d", "bucardo"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bucardo_data:
  bucardo_logs:


