web: bundle exec rails server -p ${PORT:-3001} -b 0.0.0.0
poller: bundle exec rails runner "MPDClient.new(ENV['MPD_HOST'] || 'localhost', (ENV['MPD_PORT'] || 6600).to_i, ENV['MPD_PASSWORD']).start_polling"
